name: Assigned Issue Automation

on:
  issues:
   types: [assigned]

jobs: 
  issue-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with: 
          project: resumaker
          column: In Progress
          repo-token: ${{secrets.PAO}}