name: create new issue in board

on:
  issues:
    types: [opened, assigned]
    
jobs:
  automate-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: github.event.action == 'opened'
        with: 
          project: resumaker
          column: To Do
          repo-token: ${{secrets.PAO}}
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: github.event.action == 'assigned'
        with: 
          project: resumaker
            column: In Progress
            repo-token: ${{secrets.PAO}}
        